$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$desktop = Join-Path $root 'desktop'
$ui = Join-Path $desktop 'dist-ui'
$appSrc = Join-Path $root 'web\app'
$atSrc = Join-Path $root 'web\alphatab'

if (-not (Test-Path $appSrc)) { throw "missing web/app at $appSrc" }
if (-not (Test-Path $atSrc)) { throw "missing web/alphatab at $atSrc" }

if (Test-Path $ui) { Remove-Item $ui -Recurse -Force }
New-Item -ItemType Directory -Path $ui | Out-Null

Write-Host "Copy web/app -> dist-ui/app"
Copy-Item $appSrc (Join-Path $ui 'app') -Recurse -Force
Write-Host "Copy web/alphatab -> dist-ui/alphatab"
Copy-Item $atSrc (Join-Path $ui 'alphatab') -Recurse -Force

Get-ChildItem (Join-Path $ui 'app') -Recurse -Include *.test.mjs,*.test.js | Remove-Item -Force -ErrorAction SilentlyContinue

$apiOrigin = if ($env:BIUPRO_API_ORIGIN) {
  $env:BIUPRO_API_ORIGIN.TrimEnd('/')
} elseif ($env:BIUPRO_DESKTOP_LOCAL -eq '1') {
  'http://127.0.0.1:8091'
} else {
  # Release desktop must talk to the same host that owns WeChat/Google callbacks.
  'https://www.biunow.cn'
}
$configJs = @"
/* Generated by desktop/scripts/prepare-ui.ps1 — do not edit */
window.__BIUPRO_DESKTOP_APP__ = true;
window.__BIUPRO_API_ORIGIN__ = $(ConvertTo-Json $apiOrigin);
document.documentElement.classList.add('is-desktop');
function __biunoteShowWinControls() {
  var el = document.getElementById('win-controls');
  if (el) { el.hidden = false; el.removeAttribute('hidden'); }
}
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', __biunoteShowWinControls);
} else {
  __biunoteShowWinControls();
}
"@
$utf8 = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText((Join-Path $ui 'desktop-config.js'), $configJs, $utf8)

Write-Host "Bundle desktop-bridge.js"
Push-Location $desktop
try {
  npx --yes esbuild ./bridge/main.js --bundle --format=esm --platform=browser --outfile=./dist-ui/desktop-bridge.js
  if ($LASTEXITCODE -ne 0) { throw "esbuild failed" }
} finally {
  Pop-Location
}

function Inject-DesktopAssets([string]$htmlPath) {
  $raw = [System.IO.File]::ReadAllText($htmlPath)
  if ($raw -notmatch 'desktop-config\.js') {
    $raw = $raw -replace '(<head\b[^>]*>)', "`$1`n  <script src=`"/desktop-config.js`"></script>"
  }
  if ($raw -notmatch 'desktop-bridge\.js') {
    $raw = $raw -replace '(<head\b[^>]*>)', "`$1`n  <script type=`"module`" src=`"/desktop-bridge.js`"></script>"
  }
  [System.IO.File]::WriteAllText($htmlPath, $raw, $utf8)
}

$appIndex = Join-Path $ui 'app\index.html'
$playIndex = Join-Path $ui 'app\play.html'
Inject-DesktopAssets $appIndex
if (Test-Path $playIndex) { Inject-DesktopAssets $playIndex }

# Tauri loads dist-ui/index.html — use the real app as entry (no JS redirect).
# Absolute /app/... asset paths still resolve from the custom-protocol root.
Copy-Item $appIndex (Join-Path $ui 'index.html') -Force

Write-Host "dist-ui ready (API origin: $apiOrigin; entry=app shell)"
